azure:
  cosmos:
#    uri: https://127.0.0.1:8081
#    key: this key is hard coded in org.testcontainers.containers.CosmosDBEmulatorContainer#getEmulatorKey()
    database: Assets
    connection-mode: direct
    consistency-level: eventual
    validate-uri: false
